const SocketList: Socket[] = [
    { id: 118, name: '원한', class:''},
    { id: 249, name: '기습의 대가', class:''},
    { id: 141, name: '예리한 둔기', class:''},
    { id: 109, name: '정기 흡수', class:''},
    { id: 291, name: '일격필살', class:'스트라이커'},
    { id: 292, name: '오의난무', class:'스트라이커'},
    { id: 299, name: '아드레날린', class:''},
    { id: 254, name: '돌격대장', class:''},
    { id: 255, name: '각성', class:''},
    { id: 121, name: '슈퍼 차지', class:''},
    { id: 240, name: '중갑 착용', class:''},
    { id: 286, name: '갈증', class:'리퍼'},
    { id: 243, name: '강령술', class:''},
    { id: 129, name: '강화 무기', class:'데빌헌터'},
    { id: 242, name: '강화 방패', class:''},
    { id: 288, name: '결투의 대가', class:''},
    { id: 225, name: '고독한 기사', class:'워로드'},
    { id: 125, name: '광기', class:'버서커'},
    { id: 188, name: '광전사의 비기', class:'버서커'},
    { id: 134, name: '구슬동자', class:''},
    { id: 123, name: '굳은 의지', class:''},
    { id: 190, name: '극의: 체술', class:'인파이터'},
    { id: 142, name: '급소 타격', class:''},
    { id: 302, name: '긴급구조', class:''},
    { id: 199, name: '넘치는 교감', class:''},
    { id: 287, name: '달의 소리', class:'리퍼'},
    { id: 238, name: '달인의 저력', class:''},
    { id: 258, name: '두 번째 동료', class:'호크아이'},
    { id: 168, name: '마나 효율 증가', class:''},
    { id: 251, name: '마나의 흐름', class:''},
    { id: 281, name: '멈출 수 없는 충동', class:'데모닉'},
    { id: 253, name: '바리케이드', class:''},
    { id: 279, name: '버스트', class:'블레이드'},
    { id: 246, name: '번개의 분노', class:''},
    { id: 245, name: '부러진 뼈', class:''},
    { id: 196, name: '분노의 망치', class:'디스트로이어'},
    { id: 236, name: '분쇄의 주먹', class:''},
    { id: 235, name: '불굴', class:''},
    { id: 290, name: '사냥의 시간', class:''},
    { id: 198, name: '상급 소환사', class:'서머너'},
    { id: 244, name: '선수필승', class:''},
    { id: 256, name: '세맥타통', class:'기공사'},
    { id: 300, name: '속전속결', class:''},
    { id: 248, name: '승부사', class:''},
    { id: 298, name: '시선 집중', class:''},
    { id: 237, name: '실드 관통', class:''},
    { id: 282, name: '심판자', class:'홀리나이트'},
    { id: 284, name: '아르데타인의 기술', class:'스카우터'},
    { id: 111, name: '안정된 상태', class:''},
    { id: 107, name: '약자 무시', class:''},
    { id: 110, name: '에테르 포식자', class:''},
    { id: 239, name: '여신의 가호', class:''},
    { id: 257, name: '역천지체', class:'기공사'},
    { id: 193, name: '연속 포격', class:'블래스터'},
    { id: 127, name: '오의 강화', class:'배틀마스터'},
    { id: 280, name: '완벽한 억제', class:'데모닉'},
    { id: 140, name: '위기 모면', class:''},
    { id: 278, name: '잔재된 기운', class:'블레이드'},
    { id: 247, name: '저주받은 인형', class:''},
    { id: 301, name: '전문의', class:''},
    { id: 224, name: '전투 태세', class:'워로드'},
    { id: 195, name: '절실한 구원', class:'바드'},
    { id: 276, name: '절정', class:'창술사'},
    { id: 277, name: '절제', class:'창술사'},
    { id: 293, name: '점화', class:'점화'},
    { id: 303, name: '정밀 단도', class:''},
    { id: 259, name: '죽음의 습격', class:'호크아이'},
    { id: 197, name: '중력 수련', class:'디스트로이어'},
    { id: 194, name: '진실된 용맹', class:'바드'},
    { id: 285, name: '진화의 유산', class:'스카우터'},
    { id: 295, name: '질량 증가', class:''},
    { id: 189, name: '초심', class:'배틀마스터'},
    { id: 167, name: '최대 마나 증가', class:''},
    { id: 296, name: '추진력', class:''},
    { id: 283, name: '축복의 오라', class:'홀리나이트'},
    { id: 191, name: '충격 단련', class:'인파이터'},
    { id: 297, name: '타격의 대가', class:''},
    { id: 202, name: '탈출의 명수', class:''},
    { id: 241, name: '폭발물 전문가', class:''},
    { id: 289, name: '피스메이커', class:'건슬링어'},
    { id: 192, name: '핸드거너', class:'데빌헌터'},
    { id: 130, name: '화력 강화', class:'블래스터'},
    { id: 294, name: '환류', class:'소서리스'}
    { id: 201, name: '황제의 칙령', class:'아르카나'},
    { id: 200, name: '황후의 은총', class:'아르카나'},

]


export interface Socket {
        id: number;
        name: string;
        class: string;
}

export default SocketList;
